### PR TITLE
new branch code commit

### PR DESCRIPTION
**Pull request by nagarjunakadiri88**
Hi Team 

add new code to branch X.
please review code and pull to mater branch.

thanks.

### CODE REVIEW

**Comment by nagarjunakadiri19** [comment]
hi X

please add one more statement .

**Comment by nagarjunakadiri88** [comment]
updated code please check once

1.

**Comment by nagarjunakadiri88** [comment]
code good

**Comment by nagarjunakadiri88** [comment]
commit to master branch

**Pull request merged**
